from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter

import os


def generate_report(
    total_reviews,
    positive_reviews,
    negative_reviews
):

    # =========================
    # CREATE REPORT FOLDER
    # =========================

    os.makedirs(
        "reports/generated_reports",
        exist_ok=True
    )

    # =========================
    # PDF FILE PATH
    # =========================

    pdf_path = (
        "reports/generated_reports/"
        "TravelIQ_Executive_Report.pdf"
    )

    # =========================
    # PDF DOCUMENT
    # =========================

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # =========================
    # TITLE
    # =========================

    title = Paragraph(
        "<b>TravelIQ AI Executive Report</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(
        Spacer(1, 20)
    )

    # =========================
    # KPI SUMMARY
    # =========================

    summary = Paragraph(
        f"""
        <b>Total Reviews:</b> {total_reviews}<br/>
        <b>Positive Reviews:</b> {positive_reviews}<br/>
        <b>Negative Reviews:</b> {negative_reviews}
        """,
        styles["BodyText"]
    )

    elements.append(summary)

    elements.append(
        Spacer(1, 20)
    )

    # =========================
    # AI INSIGHTS
    # =========================

    insights = Paragraph(
        """
        <b>AI Business Insights</b><br/><br/>

        • Customers strongly value location and comfort.<br/>
        • Staff behavior significantly impacts satisfaction.<br/>
        • Pricing inconsistency contributes to negative sentiment.<br/>
        • Room quality and cleanliness affect retention and loyalty.<br/>
        • Sentiment analysis indicates strong operational strengths with selective improvement areas.
        """,
        styles["BodyText"]
    )

    elements.append(insights)

    elements.append(
        Spacer(1, 20)
    )

    # =========================
    # RECOMMENDATIONS
    # =========================

    recommendations = Paragraph(
        """
        <b>Strategic Recommendations</b><br/><br/>

        • Improve room quality consistency.<br/>
        • Increase pricing transparency.<br/>
        • Continue staff hospitality training.<br/>
        • Use AI monitoring for customer sentiment tracking.<br/>
        • Monitor negative sentiment trends regularly.
        """,
        styles["BodyText"]
    )

    elements.append(recommendations)

    elements.append(
        Spacer(1, 20)
    )

    # =========================
    # FINAL NOTE
    # =========================

    footer = Paragraph(
        """
        <b>Generated By:</b> TravelIQ AI<br/>
        AI-Powered Travel Intelligence & Decision Copilot
        """,
        styles["Italic"]
    )

    elements.append(footer)

    # =========================
    # BUILD PDF
    # =========================

    doc.build(elements)

    return pdf_path